# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kulupu
email: hi@that.world
description: > # this means to ignore newlines until "baseurl:"
  Substrate Proof of Work
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kulupu.network" # the base hostname & protocol for your site
permalink: pretty
safe: true
author:
  name: Wei Tang
  email: hi@that.world

# Build settings
markdown: kramdown

plugins_dir: common/_plugins
layouts_dir: common/_layouts
includes_dir: common/_includes
sass:
  sass_dir: common/_sass
